# OrangeFox Maintainer Config for nabu

# 必须的版本变量
FOX_VERSION_MAJOR := R11.1
FOX_MAINTAINER_PATCH_VERSION := _5

# 建议的 OrangeFox 配置
OF_MAINTAINER := AviderMin
OF_TARGET_DEVICES := nabu
OF_USE_MAGISKBOOT := 1
OF_DISABLE_MIUI_OTA_BY_DEFAULT := 1
OF_USE_NEW_MAGISKBOOT := 1
OF_SKIP_MULTIUSER_FOLDERS_BACKUP := 1
OF_QUICK_BACKUP_LIST := /boot;/data;

# 显示分辨率
OF_SCREEN_H := 2000
OF_SCREEN_W := 1200
