name: 🦊 OrangeFox for nabu - 构建

# Credits to:
# https://github.com/TeamWin
# https://gitlab.com/OrangeFox
# https://github.com/azwhikaru for Recovery Builder Template
# And all Contributors in every repositories I used

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'OrangeFox 清单分支'
        required: true
        default: '12.1'
        type: choice
        options:
        - 14.1
        - 12.1
      DEVICE_TREE:
        description: 'OrangeFox 设备树'
        required: true
        default: 'https://github.com/AviderMin/android_device_xiaomi_nabu-OFRP'
      DEVICE_TREE_BRANCH:
        description: 'OrangeFox 设备树分支'
        required: true
        default: 'fox_12.1'
      DEVICE_PATH:
        description: '输入你的设备路径'
        required: true
        default: 'device/xiaomi/nabu'
      DEVICE_NAME:
        description: '输入你的设备代号'
        required: true
        default: 'nabu'
      BUILD_TARGET:
        description: '选择你的构建目标'
        required: true
        default: 'boot'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot
      MAGISK_VERSION:
        description: '选择你的Magisk版本'
        required: true
        default: 'MagiskAlpha'
        type: choice
        options:
        - Magisk
        - MagiskAlpha
        - MagiskDelta
      OF_MAINTAINER:
        description: '输入维护者名称'
        required: true
        default: 'AviderMin'

jobs:
  build:
    name: 🏗️ 构建 OrangeFox by ${{ github.actor }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OF_MAINTAINER: ${{ inputs.OF_MAINTAINER }}
    permissions:
      contents: write
    steps:
    - name: 🛒 检出代码
      uses: actions/checkout@v4
              
    - name: 🧹 清理空间
      uses: rokibhasansagar/slimhub_actions@main

    - name: 💾 设置交换空间
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24
      
    - name: 🛠️ 构建环境
      run: |
        sudo apt install aria2 -y
        git clone https://gitlab.com/OrangeFox/misc/scripts.git -b master
        cd scripts
        sudo bash setup/android_build_env.sh
      
    - name: 📜 建立清单
      if: inputs.MANIFEST_BRANCH == '12.1' || inputs.MANIFEST_BRANCH == '14.1'
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
        cd ${GITHUB_WORKSPACE}/OrangeFox
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git clone https://gitlab.com/OrangeFox/sync.git -b master
        cd sync
        ./orangefox_sync.sh --branch ${{ inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
    - name: 📥 克隆设备树
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
        git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./${{ inputs.DEVICE_PATH }}
        cd ${{ inputs.DEVICE_PATH }}
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
    - name: ⚡ 更新 OrangeFox 的内置 Magisk
      run: |
        git clone https://github.com/ymdzq/twrp_prebuilt ~/twrp_prebuilt
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/${{ inputs.DEVICE_PATH }}
        if ! grep -q 'FOX_USE_SPECIFIC_MAGISK_ZIP' vendorsetup.sh; then (echo 'export FOX_USE_SPECIFIC_MAGISK_ZIP=~/twrp_prebuilt/Magisk/${{ inputs.MAGISK_VERSION }}.apk'>>vendorsetup.sh && echo "Added FOX_USE_SPECIFIC_MAGISK_ZIP in vendorsetup.sh"); else sed -i 's/.*export FOX_USE_SPECIFIC_MAGISK_ZIP.*/export FOX_USE_SPECIFIC_MAGISK_ZIP=\~\/twrp_prebuilt\/Magisk\/${{ inputs.MAGISK_VERSION }}.apk/' vendorsetup.sh; fi
    - name: 🔨 构建 OrangeFox
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
        set +e
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export OF_MAINTAINER=${{ inputs.OF_MAINTAINER }}
        export FOX_USE_NANO_EDITOR=1
        set -e
        lunch twrp_${{ inputs.DEVICE_NAME }}-eng && make clean && mka adbd ${{ inputs.BUILD_TARGET }}image
    - name: 🏷️ 设置发布属性
      run: |
        echo "BUILD_DATE=$(TZ=Asia/Manila date +%Y%m%d)" >> $GITHUB_ENV
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
    - name: 📦 处理输出文件
      run: |
        OUT_DIR=${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/target/product/${{ inputs.DEVICE_NAME }}
        for f in "$OUT_DIR"/OrangeFox*.img "$OUT_DIR"/OrangeFox*.zip; do
          [ -e "$f" ] || continue
          base=$(basename "$f")
          ext="${base##*.}"
          name="${base%.*}"
          mv "$f" "$OUT_DIR/${name}-${BUILD_DATE}.${ext}"
        done
      env:
        BUILD_DATE: ${{ env.BUILD_DATE }}
    - name: 🚀 上传至 Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.img
          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.zip
        name: OrangeFox Recovery for ${{ inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          ## OrangeFox Recovery Build - Unofficial
          Build: fox_${{ inputs.MANIFEST_BRANCH }}
          Device: [Device Tree/Branch](${{ inputs.DEVICE_TREE }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
          Commit: Most recent [commit](${{ inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
          Maintainer: ${{ inputs.OF_MAINTAINER }}